version: '3.4'
services:
  appsvr:
    #image: 38leinad/wlp-javaee7-jdbc:latest
    #image: openliberty/open-liberty:javaee7
    image: websphere-liberty:javaee7
    ports:
     - "80:9080"
    volumes:
     - "${PROJECT}/build/libs/:/config/dropins/"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9080/hello/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s