version: '3.4'
services:
  appsvr:
    image: 38leinad/was-9
    ports:
     - "80:9080"
     - "9060:9060"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - "${PROJECT}/build/libs/:/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/monitoredDeployableApps/servers/server1/"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9080/hello/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s